config/routes.rb
Ticketee::Application.routes.draw do
  root :to => "projects#index"
  resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def new
    @project = Project.new
  end


  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end

  def show
    @project = Project.find(params[:id])
  end
  private
  def project_params
    params.require(:project).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link data-turbolinks-track="true"
  href="/assets/application.css?body=1"
  media="all"
  rel="stylesheet" />
  <link data-turbolinks-track="true"
  href="/assets/projects.css?body=1"
  media="all"
  rel="stylesheet" />
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
  <% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
  <% end %>
</body>
</html>

app/views/projects/index.html.haml
%h2 Hello world!!
= link_to "New Project", new_project_path 

app/views/projects/new.html.haml
%h2 New Project
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :description
    %br/
    = f.text_field :description
    = f.submit

app/views/projects/show.html.haml
- @title = "TextMate 2 - Projects - Ticketee" 
- title(@project.name, "Projects") 
= @project.name 